services:
  app:
    build: .
    network_mode: "host"
    environment:
      - NODE_ENV=production
      - DB_NAME=jmaia
      - DB_USER=postgres
      - DB_PASS=morormoro23
      - DB_HOST=127.0.0.1
      - DB_PORT=5432
      - DB_DIALECT=postgres
      - JWT_SECRET=nTYG5vCz@9U!x7kDM*WnR#4qA6dZsL0g
      - ADMIN_SECRET=F#8Qm$2cZVb@9wYpK!XfR%3gLbU5jS0h
      - API_BASE_URL=https://api.technologytanda.com/api
      # (add other variables as needed)
    # No need for 'ports' or 'volumes' when using host mode

